# Generated by Django 5.2.4 on 2025-08-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplesearch',
            name='weather_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
